name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Locate and unzip your app ZIP
      - name: Locate ZIP (repo root)
        id: zip
        run: |
          ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
          if [ -z "$ZIP" ]; then
            echo "No .zip file found in repo root"; exit 1
          fi
          echo "zip=$ZIP" >> "$GITHUB_OUTPUT"
          echo "Found ZIP: $ZIP"

      - name: Unzip project
        run: |
          rm -rf project
          unzip -q "${{ steps.zip.outputs.zip }}" -d project
          echo "Unzipped into ./project"
          ls -R project | head -50

      # 2. Detect Gradle project root
      - name: Detect Gradle project root
        id: gradleroot
        run: |
          cd project
          ROOT=$(find . -maxdepth 3 -type f \( -name "settings.gradle" -o -name "build.gradle" -o -name "build.gradle.kts" \) -print -quit | xargs -r dirname)
          if [ -z "$ROOT" ]; then
            echo "Could not find a Gradle project"; exit 1
          fi
          echo "dir=$PWD/$ROOT" >> "$GITHUB_OUTPUT"
          echo "Gradle root: $PWD/$ROOT"

      # 3. Set up JDK + Android SDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. Build using system Gradle (no wrapper needed)
      - name: Build Debug APK
        working-directory: ${{ steps.gradleroot.outputs.dir }}
        run: |
          gradle --version
          if gradle -q :app:tasks --all >/dev/null 2>&1; then
            gradle :app:assembleDebug
          else
            gradle assembleDebug
          fi

      # 5. Upload APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/bundle/debug/*.aab
          if-no-files-found: warn
