name: Android CI (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Pin Gradle to a stable version (avoids Gradle 9.x incompat errors)
      - name: Set up Gradle 8.2.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
          cache-read-only: false

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platforms;android-33" "build-tools;33.0.1" > /dev/null
          yes | sdkmanager --licenses

      # Build with wrapper if present, otherwise use the system gradle (8.2.1)
      - name: Build (use wrapper if present, otherwise system gradle)
        run: |
          if [ -x "./gradlew" ]; then
            echo "Using project Gradle wrapper"
            ./gradlew --version
            ./gradlew assembleDebug
          else
            echo "No wrapper found — using system Gradle 8.2.1"
            gradle --version
            gradle assembleDebug
          fi

      - name: Upload Debug APK(s)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: |
            **/app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/debug/*.apk
